### PR TITLE
Fix shades remotes

### PR DESCRIPTION
**Pull request by bdraco**
- These devices have multiple button groups (https://blinds.lowes.com/product/detail.action?sku=Lutron-Serena-RF-4-Group-Remote-Control)

- Fixes KeyError when fetching button devices (when it hit the second group)

### CODE REVIEW

**Comment by bdraco** [comment]
Pico remotes work great.  Unfortunately I hit this on the 3rd instance when I deployed to my production machines for testing.

The shade remotes have 5 button groups.

**Comment by bdraco** [comment]
```
{
			"href": "/device/43",
			"Name": "Shade Remote",
			"FullyQualifiedName": ["Upstairs Hall", "Shade Remote"],
			"Parent": {
				"href": "/project"
			},
			"SerialNumber": XXXXXXX,
			"ModelNumber": "CS-YJ-4GC-WH",
			"DeviceType": "FourGroupRemote",
			"ButtonGroups": [{
				"href": "/buttongroup/22"
			}, {
				"href": "/buttongroup/23"
			}, {
				"href": "/buttongroup/24"
			}, {
				"href": "/buttongroup/25"
			}, {
				"href": "/buttongroup/26"
			}],
			"AssociatedArea": {
				"href": "/area/7"
			},
			"LinkNodes": [{
				"href": "/device/43/linknode/42"
			}],
			"DeviceRules": [{
				"href": "/devicerule/32"
			}]
		}
```

**Comment by bdraco** [comment]
@mdonoughe Sorry I didn't catch this in the first round of testing (I don't have the shades remotes on my primary or secondary instances), but it look like we need a 0.12.1.

**Comment by mdonoughe** [comment]
This PR changes the `buttongroup` to `button_groups` so I extracted some of the PR into a 0.12.1 release. It probably doesn't matter because it's unlikely anybody started using the 0.12.0 released less than 24 hours ago, but 0.12.1 shouldn't contain breaking changes.

**Comment by mdonoughe** [comment]
Can you check that this works with your shade remotes before I release 0.13.0?

**Comment by bdraco** [comment]
> Can you check that this works with your shade remotes before I release 0.13.0?

I will test `0.12.1` and `dev` shortly with the shade remote

**Comment by mdonoughe** [comment]
0.12.1 I'm not too worried about. I copied the test data from this branch and fixed a KeyError. Only the buttons from each remote's first group should appear.

**Comment by bdraco** [comment]
Testing

- [x] 0.12.1 -- confirmed key error gone, no callback for button groups beyond the first (expected)
- [ ] dev -- expected key error gone, callback for button groups beyond the first

**Comment by bdraco** [comment]
Confirmed working

```
{
    "event_type": "lutron_caseta_button_event",
    "data": {
        "serial": <SNIP>,
        "type": "FourGroupRemote",
        "button_number": <SNIP>,
        "device_name": "<SNIP>",
        "area_name": "Living Room",
        "action": "press"
    },
    "origin": "LOCAL",
    "time_fired": "2021-12-05T17:11:37.714549+00:00",
    "context": {
        "id": "00b4a41fbca0a3025f5cbc72916eadd7",
        "parent_id": null,
        "user_id": null
    }
}
```

**Comment by bdraco** [comment]
Tested on second instance as well 👍

**Comment by mdonoughe** [comment]
Released as 0.13.0: https://pypi.org/project/pylutron-caseta/0.13.0/

**Pull request merged**
