### PR TITLE
Adding in support of new lutron caseta fan controller.

### PR DESCRIPTION
**Pull request by djj211**
Added new methods to set the fan speed of the new lutron fan controller (with appropriate JSON).
Modified methods to check if the level json attribute or if the FanSpeed json attribute was returned from lutron caseta smartbridge status requests. Not doing this check was causing errors when adding the new smart fan controller to the smartbridge.

Also, modified smartbridge.py so CERT_REQUIRED is the default but can be set back to none by passing in false to the create_tls method. This is because I could not connect with it required from homeassistant.

NOTE: I do use pylutron_caseta as part of homeassistant and will be adding fan support here as well. 
Also, the require ssl is not working in my homeassistant environment and I have to turn that off.

### CODE REVIEW

**Comment by cryptk** [comment]
@gurumitts any chance we could get this merged in and a new release cut out to pypi? The Home Assistant community would benefit greatly from this functionality!

**Comment by kquinsland** [comment]
@cryptk it looks like @gurumitts was last active on github ~9 months ago.  I'd like to get the ball rolling on what it might take for a home-assistant maintained fork.  Thoughts?

**Comment by djj211** [comment]
@cryptk @gurumitts I believe home-assistant wants all third party api's hosted on the pypi. So I think think the only way to get this going is to create a new fork, create a new pypi repository, and upload that. After that we can update the manifest and configuration of the home-assistant component to point to the new pylutron_caseta in the pypi.

Fairly new to HA development, but the above is my understanding. I'll see if I can find the article I read that.

**Comment by kquinsland** [comment]
@djj211 Thanks for the quick and helpful reply.

> Fairly new to HA development, but the above is my understanding. I'll see if I can find the article where I read that.

Likewise.  No stranger to Python, but HA is a *really big* codebase (1st and 3rd party code) and contributing to something with a big footprint is always a bit intimidating. If the biggest hurdle to working Caseta/fan code is the one time administrative burden of getting a fork "published" then i can probably find a few spare cycles to do just that.

**Comment by amelchio** [comment]
It's not a one time cost. If you want Home Assistant to move to your fork you must be prepared to maintain it going forward.

I see @mdonoughe made the latest commit, maybe he knows about the state of this project?

**Comment by mdonoughe** [comment]
I put some work towards https://github.com/gurumitts/pylutron-caseta/milestone/1 but I haven't heard from @gurumitts so I've been using https://github.com/mdonoughe/home-assistant-custom to get newer code with entity registry support into my home assistant.

**Comment by cryptk** [comment]
@mdonoughe I have something similar that I am doing to get this running in my home-assistant setup... So, it seems like we have 2 options... either we see if home-assistant themselves would be willing to fork and maintain the library (which from converstaions with them so far, does not seem to be likely) or "someone else" forks and maintains the library

**Comment by berkman** [comment]
would anyone be willing to help support this library?  this is functionality that would be huge for me.  nudge @gurumitts

**Comment by mcaminiti** [comment]
Any updates on where this landed? I just added a fan switch to my home and thought Home Assistant with this module supported it.  I found this thread after looking to see what I needed to do myself to get it working.

**Comment by mdonoughe** [comment]
If you want to get this running, follow these instructions except put the patched code into the deps folder: https://developers.home-assistant.io/docs/en/creating_integration_manifest.html#custom-requirements-during-development-testing

**Comment by mcaminiti** [comment]
> If you want to get this running, follow these instructions except put the patched code into the deps folder: https://developers.home-assistant.io/docs/en/creating_integration_manifest.html#custom-requirements-during-development-testing

Is the HA component already setup to handle the Fan side of it, or would I need to pull a development branch of that component too?

**Comment by djj211** [comment]
@mcaminiti The HA fan component is ready. The pull request was approved but closed because we were waiting for this pull request. The only thing I believe will need to be done on the HA PR is an update of the manifest to the new version of pylutron once complete.

https://github.com/home-assistant/home-assistant/pull/24770

I think they marked the PR as private, but I can update the manifest once ready.

**Comment by mdonoughe** [comment]
@djj211 I pushed 0.5.1 to PyPI today and created home-assistant/home-assistant#28886 for upgrading to 0.5.1 and enabling entity registry support. You should be good to create a new PR for adding fan support to Home Assistant. When merging this PR I added constants for the Caseta fan speed values you can use in the Home Assistant integration.

**Comment by djj211** [comment]
@mdonoughe Thank you for taking ownership of this, reviewing, merging, and creating the new PR in the HA repository. The community will be thankful for sure. So far everything is working in my test environment with 0.5.1 and the fan componenet. I will do some further regression testing this weekend and then reopen my PR. Thanks again.

**Pull request merged**
