### PR TITLE
Added support for Caseta Scenes (virtualbuttons)

### PR DESCRIPTION
**Pull request by kfcook**
I'm sure you're already aware, but this library is in use in Home Assistant. I've been wanting scene support in HA for quite a while, so I decided to add it into your library. I've also updated the code needed on the HA side, but we need to update this branch so the dependencies get pulled in correctly. Let me know if you have any comments about my code.

Thanks!

### CODE REVIEW

**Comment by kfcook** [comment]
Sorry about all the commits...the Travis checks are tough!

**Comment by gurumitts** [comment]
I will review this and if all looks well I will merge it this evening.  My quick look on my mobile looks good so I don't expect any issue.  Thanks for the PR!  Sorry for the delay I have been on travel.

**Comment by kfcook** [comment]
Awesome. Thanks!!

**Comment by gurumitts** [comment]
I Will have a new pypi package soon

**Comment by kfcook** [comment]
Perfect. Let me know what the new version number is and I'll update the HA files and submit my scene support branch.

**Comment by gurumitts** [comment]
pylutron_caseta-0.2.7 is live in pypi

**Pull request merged**
