### PR TITLE
Fixes #48 KeyError while setting up component

### LINKED ISSUE #48: component failed to setup with KeyError: 'Body'
Caseta component setup failed after I upgraded to home assistant 0.108.0.dev20200330, with below exception. 
```
2020-03-31 18:41:26 ERROR (MainThread) [homeassistant.setup] Error during setup of component lutron_caseta
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 171, in _async_setup_component
    hass, processed_config
  File "/usr/src/homeassistant/homeassistant/components/lutron_caseta/__init__.py", line 53, in async_setup
    await bridge.connect()
  File "/usr/local/lib/python3.7/site-packages/pylutron_caseta/smartbridge.py", line 51, in connect
    await self._login()
  File "/usr/local/lib/python3.7/site-packages/pylutron_caseta/smartbridge.py", line 363, in _login
    await self._load_occupancy_groups()
  File "/usr/local/lib/python3.7/site-packages/pylutron_caseta/smartbridge.py", line 467, in _load_occupancy_groups
    for occgroup in occgroup_json["Body"]["OccupancyGroups"]:
KeyError: 'Body'
```

### PR DESCRIPTION
**Pull request by guoyiang**

### CODE REVIEW

**Comment by swails** [comment]
Why wasn't CI run with this PR?

**Comment by guoyiang** [comment]
CI was run but seems it failed to post messages. Now CI passed...

https://travis-ci.org/github/gurumitts/pylutron-caseta/builds/669816143

**Comment by swails** [comment]
@mdonoughe , I’ll run this against my system and if it works for all of us then we should cut another release to prevent the next home assistant release from breaking.

**Comment by swails** [comment]
This works on my system.

Can you cut a new release so we can update HA before 0.108 is out the door?

**Comment by mdonoughe** [comment]
I just created https://pypi.org/project/pylutron-caseta/0.6.1/ .

**Pull request merged**
