### PR TITLE
Support Spring 2018 protocol

### LINKED ISSUE #22: New method no longer working?
I appears that something has changed on the Lutron end.  Neither the plugin nor the script to get a key are working anymore.

plugin error:
`Error during setup of component lutron_caseta
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 142, in _async_setup_component
    result = await component.async_setup(hass, processed_config)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/lutron_caseta.py", line 57, in async_setup
    yield from bridge.connect()
  File "/usr/lib/python3.6/site-packages/pylutron_caseta/smartbridge.py", line 40, in connect
    yield from self._login()
  File "/usr/lib/python3.6/site-packages/pylutron_caseta/smartbridge.py", line 281, in _login
    self._reader, self._writer = yield from self._connect()
  File "/usr/lib/python3.6/site-packages/pylutron_caseta/smartbridge.py", line 58, in _connect
    family=socket.AF_INET)
  File "/usr/lib/python3.6/site-packages/pylutron_caseta/leap.py", line 16, in open_connection
    limit=limit, **kwds)
  File "/usr/lib/python3.6/asyncio/streams.py", line 75, in open_connection
    lambda: protocol, host, port, **kwds)
  File "uvloop/loop.pyx", line 1769, in create_connection
  File "/usr/lib/python3.6/asyncio/sslproto.py", line 503, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.6/asyncio/sslproto.py", line 201, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)`

Script error:
`(general) xnappo@machine:~/homeio$ python get_lutron_cert.py
Enter the address of your Caseta bridge device: 192.168.1.xx
Traceback (most recent call last):
  File "get_lutron_cert.py", line 156, in <module>
    leap_response['Body']['PingResponse']['LEAPVersion'])
KeyError: 'Body'`

### PR DESCRIPTION
**Pull request by mdonoughe**
It looks like with the new firmware:
- certificates have been reissued
- the bridge sends some unsolicited messages on connection
- the names of devices have been prefixed with the names of rooms? My Home Assistant was not happy after patching this code in, but it could have been something I did in the Lutron app when I installed new switches a couple weeks ago.

The existing script to get the certificates should still get the certificates, despite printing an error at the end. I've put an updated copy of the script directly in the repository.

Unexpected messages are now ignored during the connection phase. If you're somehow still running the old firmware this shouldn't be a problem.

Fixes #22

### CODE REVIEW

**Comment by mdonoughe** [comment]
The Travis cache may have bad data in it. I don't think I can do anything to make that 3.4 test run succeed.

**Comment by jdeath** [comment]
New script pulls down certs without error, but cannot control

I downloaded new smartbridge.py, replaced file in cloned git zip, then did pip install. Am I missing something?

**Comment by sfnetwork** [comment]
works perfectly, my non pro lutron hub works again now.
I simply modified "smartbridge.py"

**Comment by mhofman** [comment]
For the home assistant integration, it might be a good opportunity to use the entity registry, and avoid future renames.

**Comment by glassbase** [comment]
I am up and working with this PR on non-pro.

**Comment by jdeath** [comment]
I'm up now too. thanks mdonoughe. I just did a wget into the /srv/..../pylutron-caseta/ directory

**Comment by Coolie1101** [comment]
@mdonoughe 
Many, many, many thanks.

Back up and running on non pro hub :+1:

**Comment by djrausch** [comment]
Working for me as well on non pro! 👍

**Comment by jchong** [comment]
Hey guys, I'd like to fix my lights as well.  I'm not sure what I need to download

**Comment by brettzie** [comment]
Where can I find this directory on hassio?

**Comment by Tim91084** [comment]
This does work.  Couple notes for others.  I had to delete the certs I had already in the directory, otherwise the script wouldn't fetch the new certs.  The name prefixing is annoying (had to update all my automations).  If you're looking for where to replace the smartbridge.py file and using a docker install, it's here: /usr/local/lib/python3.6/site-packages/pylutron_caseta

**Comment by gurumitts** [comment]
Ill get this merged today and push out a new version to pip today - probably this evening.

**Comment by Coolie1101** [comment]
@gurumitts 
@Tim91084 
FYI: On Hassbian, all I did was update `smartbridge,py` in `/srv/homeassistant/lib/python3.5/site-packages/pylutron_caseta`

**Comment by xnaron** [comment]
@brettzie did you get this working on hassio?  If so how? thanks

**Comment by jchong** [comment]
I'm not using hassio but I am using the docker container.  I fixed it by mounting the smartbridge.py file in docker:

/path/to/smartbridge.py:/usr/local/lib/python3.6/site-packages/pylutron_caseta/smartbridge.py

**Comment by xnaron** [comment]
@jchong Thanks I ended up doing something similar after I posted.

**Comment by marclefevre** [comment]
I am having the same issue and have tried to upgrade as follows:
```
(homeassistant) homeassistant@hassbian:/srv/homeassistant/lib/python3.5/site-packages $ pip3 install --upgrade pylutron_caseta
Looking in indexes: https://pypi.python.org/simple, https://www.piwheels.org/simple
Collecting pylutron_caseta
  Downloading https://www.piwheels.org/simple/pylutron-caseta/pylutron_caseta-0.5.0-py3-none-any.whl
myusps 1.3.2 has requirement requests==2.12.4, but you'll have requests 2.18.4 which is incompatible.
netdisco 1.2.4 has requirement zeroconf==0.19.1, but you'll have zeroconf 0.20.0 which is incompatible.
Installing collected packages: pylutron-caseta
  Found existing installation: pylutron-caseta 0.3.0
    Uninstalling pylutron-caseta-0.3.0:
      Successfully uninstalled pylutron-caseta-0.3.0
Successfully installed pylutron-caseta-0.5.0
```
Did this pick up the fix?  When I restart, I still get the configuration failure.

**Comment by pdblood** [comment]
Home assistant will reinstall the old version of pylutron-caseta when you restart it. You need to edit this file:

`./homeassistant/components/lutron_caseta.py`

and change this:

`REQUIREMENTS = ['pylutron-caseta==0.3.0']`

to this:

`REQUIREMENTS = ['pylutron-caseta==0.5.0']`

Then restart home assistant and it should pick up the change. This worked for me.

**Comment by marclefevre** [comment]
Thanks.  That worked.

**Comment by bromansamich** [comment]
Hoping someone can assist as I only started using HA a couple weeks ago; Hassio install.  When using the Web UI to navigate through the system files/folders, I can get to /usr/lib/python3.6/sitepackages.  When in sitepackages, I don't have a pylutron_caseta folder.

The folders I have are: git, gtdb, ditdb2-2.0.3.dist-info, GitPython-2.1.9.dist-info, pip, pip-9.0.1.dist-info, pkg_resources, setuptools, setuptools-28.8.0.dist-info, smmap, smmap2-2.0.3.dist-info.

I put all three of the caseta files in /config.  Anything apparent that I'm doing wrong?

Log:

```
2018-04-20 00:22:43 ERROR (MainThread) [homeassistant.setup] Error during setup of component lutron_caseta
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 142, in _async_setup_component
    result = await component.async_setup(hass, processed_config)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/lutron_caseta.py", line 57, in async_setup
    yield from bridge.connect()
  File "/usr/lib/python3.6/site-packages/pylutron_caseta/smartbridge.py", line 40, in connect
    yield from self._login()
  File "/usr/lib/python3.6/site-packages/pylutron_caseta/smartbridge.py", line 284, in _login
    yield from self._load_devices()
  File "/usr/lib/python3.6/site-packages/pylutron_caseta/smartbridge.py", line 314, in _load_devices
    for device in device_json['Body']['Devices']:
KeyError: 'Body'
```

**Pull request merged**
