### PR TITLE
Add Raise/Lower/Stop support for covers

### PR DESCRIPTION
**Pull request by bdraco**
I'm working on a Home Assistant PR to add SUPPORT_STOP to covers

### CODE REVIEW

**Comment by swails** [comment]
Did the unit tests get run for this PR?

**Comment by bdraco** [comment]
@swails 
```
 tests/test_leap.py ✓✓✓✓✓                                                                                                                                          21% ██▏       
 tests/test_smartbridge.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓                                                                                                                    100% ██████████
```
Yes

**Comment by swails** [comment]
I meant by Travis :)

**Comment by bdraco** [comment]
> I meant by Travis :)

https://travis-ci.org/github/gurumitts/pylutron-caseta

**Comment by bdraco** [comment]
https://travis-ci.org/github/gurumitts/pylutron-caseta/builds/679889646

**Comment by swails** [comment]
It looks like for some reason Travis isn't able to post back to Github with the build status -- @mdonoughe since you seem to have admin-y like rights here, can you check the settings to see if there is a problem with Travis posting bulid status back here?

**Comment by mdonoughe** [comment]
I don't know what's going on with Travis and I don't think I have access to any Travis-related settings for this repo. Hopefully it was just a temporary integration issue.

**Pull request merged**
